[package]
name = "ssh-agent"
description = "Library for implementing an SSH agent"
version = "0.0.0"
license = "MIT"
authors = ["Nicolas Trippar <ntrippar@gmail.com>"]
readme = "README.md"
edition = "2018"

[badges]
travis-ci = { repository = "sekey/ssh-agent.rs" }
codecov = { repository = "sekey/ssh-agent.rs" }

[dependencies]
byteorder = "1.2.7"
num-derive = "0.2"
num-traits = "0.2"
serde = "*"
serde_derive = "*"
bytes = "*"
tokio = "*"
tokio-uds = "*"
futures = "*"